config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :restaurants do
    collection do
      get 'search'
    end
    put :favorite, on: :member # adds favorite_restaurant_path
  end
  
  get 'users/:id', to: 'users/profiles#show', as: :profile
  get 'users/:id/edit', to: 'users/profiles#edit', as: :edit_profile
  patch 'users/:id', to: 'users/profiles#update', as: :update_profile

  root 'restaurants#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :restaurant_categories
    has_many :restaurants, through: :restaurant_categories
end

app/models/favorite_restaurant.rb
class FavoriteRestaurant < ApplicationRecord
    belongs_to :restaurant
    belongs_to :user
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    
    has_attached_file :image, styles: { medium: "900x400#", thumb: "286x180#" }, default_url: "http://via.placeholder.com/286x180",
        convert_options: {:medium => "-gravity center -extent 900x400", :thumb => "-gravity center -extent 286x180"}
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/


    has_many :restaurant_categories
    has_many :categories, through: :restaurant_categories
    accepts_nested_attributes_for :categories, reject_if: proc { |attribute| attribute['name'] === "" }
    has_many :favorite_restaurants
    has_many :favorited_by, through: :favorite_restaurants, source: :user

    #geocoded_by :full_address
    #after_validation :geocode

    def full_address
        [address1, address2, city, state, zipcode].join(', ')
    end

    scope :newest, -> { order("created_at DESC").limit(25) }
    scope :oldest, -> { order("created_at ASC").limit(25) }

    def categories_attributes=(category_attributes)
        
        category_attributes.values.each do |attribute|
            if attribute["name"] != ""
                category = Category.find_or_create_by(attribute)
                self.categories << category 
            end
        end
    end

    #def self.search(params)
    #    restaurants = Restaurant.where("name LIKE ?", "%#{params[:search]}%")
    #    restaurants = restaurants.near(params[:location]) if params[:location].present?
    #    restaurants
    #end

end

app/models/restaurant_category.rb
class RestaurantCategory < ApplicationRecord
    belongs_to :restaurant
    belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:github, :google_oauth2]
  
  has_attached_file :avatar, styles: { thumb: '150x150#' }, :default_url => "http://via.placeholder.com/150x150"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
         
  validates :username, presence: true
  validates :username, uniqueness: true

  has_many :favorite_restaurants
  has_many :favorites, through: :favorite_restaurants, source: :restaurant

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.github_data"] && session["devise.github_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    # binding.pry
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.nickname
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
    end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :favorite]
    skip_before_action :authenticate_user!, only: [:index, :show]

    def index
        # visitor_location = request.location.city
        @restaurants = Restaurant.all
    end

    def new
        @restaurant = Restaurant.new
        @categories = 3.times.collect { @restaurant.categories.build }
    end

    def create
        @restaurant = Restaurant.new(restaurant_params)
        @restaurant.submitted_by = current_user.id

        if @restaurant.save
            redirect_to restaurant_path(@restaurant)
        else
            render 'new'
        end
    end

    def show
        @favorite = FavoriteRestaurant.find_by(user: current_user, restaurant: @restaurant).present?
        @submitted = User.find(@restaurant.submitted_by)
    end

    def edit
        @categories = 3.times.collect { @restaurant.categories.build }
    end

    def update
        if @restaurant.update(restaurant_params)
            redirect_to restaurant_path(@restaurant)
        else
            render 'new'
        end
    end

    def destroy
        @restaurant.destroy
        redirect_to root_path
    end

    def favorite
        button = params[:button]
        if button == "favorite"
            current_user.favorites << @restaurant
            redirect_to restaurant_path(@restaurant)
        elsif button == "unfavorite"
            current_user.favorites.destroy(@restaurant)
            redirect_to restaurant_path(@restaurant)
        end
    end

    def search
        @restaurants = Restaurant.search(params)
    end

    private
    def set_restaurant
        @restaurant = Restaurant.find(params[:id])
    end

    def restaurant_params
        params.require(:restaurant).permit(:name, :address1, :address2, :city, :state, :zipcode, :location, :search,
            :image, :submitted_by, category_ids:[], categories_attributes: [ :id, :name ])
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

    def github
        @user = User.from_omniauth(request.env["omniauth.auth"])

        if @user.persisted?
            sign_in_and_redirect @user
        else
            session["devise.github_data"] = request.env["omniauth.auth"]
            redirect_to new_user_registration_url
        end
    end
    alias_method :google_oauth2, :github

    def failure
        redirect_to root_path
    end

end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
    before_action :set_user

    def show
    end

    def edit
    end
    
    def update
        if @user.update(profile_params)
            redirect_to profile_path(current_user)
        else
            render 'edit'
        end
    end

    private

    def set_user
        @user = current_user
    end

    def profile_params
        params.require(:user).permit(:avatar, :bio)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/_error_messages.html.erb
<% if target.errors.any? %>
<div class="error_explanation">
  <h3><%= pluralize(target.errors.count, "error") %> prevented this record from being saved:</h3>
  <ul>
  <% target.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="py-5 bg-dark">
    <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; Cuisine Pursuit 2018</p>
    </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Cuisine Pursuit", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <a href="#" class="nav-link">All Restaurants</a>
      </li>
    </ul>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.username %></a>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

            <%= link_to "New Restaurant", new_restaurant_path, class: "dropdown-item" %>

            <div class="dropdown-divider"></div>

            <%= link_to "Profile", profile_path(current_user), class: "dropdown-item" %>
            <%= link_to "Account Settings", edit_user_registration_path(current_user), class: "dropdown-item" %>

            <div class="dropdown-divider"></div>

            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>

          </div>

        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
        </li>              
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CuisinePursuitV2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, html: { multipart: true } do |f| %>
<%= render 'layouts/error_messages', target: @restaurant %>
    <div class="form-group row">
        <%= f.label :image, class: "col-sm-2 col-form-label"%>
        <div class="col-sm-10">
            <%= f.file_field :image, class: "form-control" %>
        </div>
    </div>
    <div class="form-group row">
        <%= f.label :name, class: "col-sm-2 col-form-label"%>
        <div class="col-sm-10">
            <%= f.text_field :name, class: "form-control" %>
        </div>
    </div>
    <div class="form-group row">
        <%= f.label :address1, "Address Line 1", class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
            <%= f.text_field :address1, class: "form-control" %>
        </div>
    </div> 
    <div class="form-group row">
        <%= f.label :address2, "Address Line 2", class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
            <%= f.text_field :address2, class: "form-control" %>
        </div>
    </div> 
    <div class="form-group row">
        <%= f.label :city, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
            <%= f.text_field :city, class: "form-control" %>
        </div>
    </div> 
    <div class="form-group row">
        <%= f.label :state, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
            <%= f.text_field :state, class: "form-control" %>
        </div>
    </div> 
    <div class="form-group row">
        <%= f.label :zipcode, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
            <%= f.text_field :zipcode, class: "form-control" %>
        </div>
    </div> 
    <div class="form-group row">
        <%= f.label :category, class: "col-sm-2 col-form-label" %>  
        <div class="col-sm-10">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
        </div>  
        <!-- , {selected: @restaurant.category_id}, {multipart: true} -->
    </div>
    <div class="form-group">
        <%= f.fields_for :categories, @categories do |category_field| %>
            <div class="form-group">
                <%= category_field.label "New Category" %>
                <%= category_field.text_field :name %>
            </div>
        <% end %>
    </div> 
    <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/restaurants/_restaurant_card.html.erb
<div class="col-lg-4 mb-4">
    <div class="card text-center panel">
        <%= image_tag restaurant.image.url(:thumb), class: "card-img-top", alt: "card-img-top" %>
        <div class="card-header">
            <%= link_to restaurant.name, restaurant_path(restaurant) %>
        </div>
        <div class="card-body">
            <p class="card-text">This should be a description, I think.</p>
            <%= link_to "View Restaurant", restaurant_path(restaurant), class: "btn btn-primary" %>
        </div>
        <div class="card-footer">
            <ul class="list-inline">
                <% restaurant.categories.each do |category| %>
                    <li class="list-inline-item"><%= category.name %></li>
                <% end %>
            </ul>
        </div>
    </div>
</div>

app/views/restaurants/edit.html.erb
<div class="container-fluid form-container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="form-style panel p-3">
                <div class="panel-heading">
                    <h1>Edit Restaurant</h1>
                    <%= link_to "Back", restaurants_path, class: "btn btn-secondary" %>
                </div>
                <div class="panel-body py-3">
                    <%= render 'form' %>
                </div>
                <%= link_to "Delete", restaurant_path(@restaurant), method: :delete %>
            </div>
        </div>
    </div>
</div>

app/views/restaurants/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-8">
      <div class="homepage-display panel">    
        <img class="img-fluid rounded" src="http://placehold.it/900x400" alt="">
      </div>
    </div>
    <div class="col-lg-4">
      <div class="search-form panel">
        <div class="form-style">
          <div class="panel-heading my-1">
            <h1>Search</h1>
          </div>
          <div class="panel-body pl-2">
            <%= form_with url: search_restaurants_path, method: :get, local: true do |f| %>
              <div class="form-group row">
                <%= f.label :search, "Name", class: "col-sm-3 col-form-label" %>
                  <div class="col-sm-8">
                    <%= f.text_field :search, class: "form-control" %>
                  </div>
                </div>
                <div class="form-group row">
                  <%= f.label :location, class: "col-sm-3 col-form-label" %>
                  <div class="col-sm-8">
                    <%= f.text_field :location, class: "form-control" %>
                  </div>
                </div>
                <div class="form-group row">
                  <%= f.label :category, class: "col-sm-3 col-form-label" %>
                    <div class="col-sm-8 py-2">
                      <%= f.collection_select :category, Category.all, :id, :name, include_blank: "Not functional", class: "form-control" %>
                    </div>
                  </div>
                  <%= f.submit "Search", name: nil, class: "btn btn-primary mb-2" %>
                <% end %>
              </div>
            </div>          
          </div>
        </div>
      </div>
      <div class="card text-white bg-secondary my-4 text-center">
        <div class="card-body">
          <p class="text-white m-0">This call to action card is a great place to showcase some important information or display a clever tagline!</p>
        </div>
      </div>
    <div class="row">
      <% @restaurants.each do |restaurant| %>
        <%= render 'restaurant_card', restaurant: restaurant %>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container-fluid form-container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="form-style panel p-3">
                <div class="panel-heading">
                    <h1>New Restaurant</h1>
                    <%= link_to "Back", restaurants_path, class: "btn btn-secondary" %>
                </div>
                <div class="panel-body py-3">
                    <%= render 'form' %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/restaurants/search.html.erb
<div class="container-fluid">
  <div class="card text-center">
    <div class="card-body">
      <h2><%= params[:search] %> - <%= params[:location] %></h2>
    </div>
  </div>
  <div class="row my-3">
    <% @restaurants.each do |restaurant| %>
      <%= render 'restaurant_card', restaurant: restaurant %>
    <% end %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container-fluid">
    <div class="col-lg-10 offset-lg-1">
        <div class="card text-center">
            <%= image_tag @restaurant.image.url(:medium), class: "card-img-top image-fluid", alt: "card-img-top" %>
            <div class="card-header display-4">
                <%= @restaurant.name %>
            </div>
            <div class="card-body row">
                <div class="col-sm-6">
                    <div class="restaurant-information">
                        <h3>Restaurant Information</h3>
                        <p><%= @restaurant.address1 %></p>
                        <p><%= @restaurant.address2 %></p>
                        <p><%= @restaurant.city %>, <%= @restaurant.state %> <%= @restaurant.zipcode %></p>                
                    </div>
                    <div class="restaurant-categories">
                        <h3>Categories</h3>
                        <% @restaurant.categories.each do |category| %>
                            <%= category.name %>
                        <% end %>
                    </div>
                    <div class="restaurant-details">
                        <h3>Not Sure Where To Put This Yet</h3>
                        <% if user_signed_in? %>
                            <% if @favorite %>
                                <%= link_to "Unfavorite", favorite_restaurant_path(@restaurant, button: "unfavorite"), method: :put, class: "btn btn-primary" %>
                            <% else %>
                                <%= link_to "Favorite", favorite_restaurant_path(@restaurant, button: "favorite"), method: :put, class: "btn btn-primary" %>
                            <% end %>
                        <% end %>         
                        <p> Favorites: <%= @restaurant.favorited_by.count %></p>
                        <small>Submitted By: <%= @submitted.username %></small>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div id="map" class="map">
                        <iframe width="400" height="300" frameborder="0" style="border:0" 
                        src="https://www.google.com/maps/embed/v1/place?key=AIzaSyA4n5tVlG_g_QI0d1uTloOLU4bFUz8GrOA&q=<%= @restaurant.latitude %>,<%= @restaurant.longitude %>" 
                        allowfullscreen></iframe>
                    </div>
                <h3>Google Maps Location</h3>

                </div>
            </div>
            <div class="card-footer">
                <div class="btn-group">
                    <%= link_to "Back", restaurants_path, class: "btn btn-secondary" %>
                    <%= link_to "Edit", edit_restaurant_path(@restaurant), class: "btn btn-secondary" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/profiles/edit.html.erb
<div class="container-fluid form-container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="form-style panel p-3">
                <div class="panel-heading">
                    <h1>Edit Profile</h1>
                    <%= link_to "Back", profile_path(current_user), class: "btn btn-primary" %>
                </div>
                <div class="panel-body p-3">
                    <%= image_tag @user.avatar.url(:thumb), class: "pb-3" %>
                    <%= form_for @user, url: profile_path(@user), html: { multipart: true } do |f| %>
                        <div class="field form-group row">
                            <%= f.label :avatar, "Avatar", class: "col-sm-2 col-form-label"%>
                            <div class="col-sm-10">
                                <%= f.file_field :avatar, class: "form-control" %>
                            </div>
                        </div>

                        <div class="field form-group row">
                            <%= f.label :bio, class: "col-sm-2 col-form-label"%>
                            <div class="col-sm-10">
                                <%= f.text_area :bio, class: "form-control" %>
                            </div>     
                        </div>
                        <%= f.submit "Update", class: "btn btn-primary" %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/profiles/show.html.erb
<div class="container-fluid form-container">
    <div class="row">
        <div class="col-lg-10 offset-lg-1 panel">
            <div class="row p-3">
                <div class="col-md-4">
                    <%= image_tag @user.avatar.url(:thumb), class: "user-profile-thumb" %>
                </div>
                <div class="col-md-8">
                    <div>
                        <h1><%= @user.username %></h1>
                        <h4>Bio</h4>
                        <p><%= @user.bio %></p>
                        
                        <div class="btn-group">
                            <%= link_to "Edit Profile", edit_profile_path(current_user), class: "btn btn-secondary" %>
                            <%= link_to "Account Settings", edit_user_registration_path(current_user), class: "btn btn-secondary" %>
                            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-secondary" %>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mb-5">
        <div class="col-md-10 offset-md-1 panel">
            <div class="user-favorites">
                <h1 class="text-center">Favorites</h1>
                <% @user.favorites.each do |favorite| %>
                    <%= favorite.name %>
                <% end %>
            </div>  
        </div>
    </div>
</div>